In [24]:
import numpy as np
import pandas as pd
from pathlib import Path
import os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn import preprocessing

In [3]:
#Import files
from google.colab import files
uploaded = files.upload()

Saving heart_attack_final_table.csv to heart_attack_final_table.csv

In [4]:
#Read file
file_path = Path('heart_attack_final_table.csv')
df = pd.read_csv(file_path)

In [ ]:
df

,id,ever_overweight,blood_transfusion_yr,heart_attack_age,fatty_liver,liver_fibrosis,liver_cirrhosis,liver_viral_hepatitis,liver_autoimmune_hepatitis,other_liver_disease,...,stroke,thyroid,liver_disease,gallbladder_pr,Total_Cholesterol_mg_dL,Frequency_of_Drinking,Drinks_per_Day,Work,Recreational,100_Cigarettes
0,109266.0,1,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,195.0,10.0,1.0,0,1,0
1,109274.0,1,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,105.0,4.0,2.0,1,0,0
2,109292.0,0,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,172.0,4.0,6.0,0,0,0
3,109297.0,0,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,214.0,6.0,2.0,1,0,0
4,109307.0,0,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,161.0,9.0,1.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5497,124815.0,0,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,203.0,3.0,1.0,1,1,1
5498,124817.0,1,NaN,NaN,0,0,0,0,0,1,...,0,0,0,0,200.0,3.0,2.0,1,0,0
5499,124818.0,1,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,234.0,9.0,2.0,0,0,0
5500,124821.0,0,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,155.0,5.0,5.0,1,0,0
5501,124822.0,0,NaN,70.0,0,0,0,0,0,0,...,0,0,0,0,171.0,6.0,2.0,0,1,0

In [5]:
df.info

<bound method DataFrame.info of             id  ever_overweight  blood_transfusion_yr  heart_attack_age  \
0     109266.0                1                   NaN               NaN
1     109274.0                1                   NaN               NaN
2     109292.0                0                   NaN               NaN
3     109297.0                0                   NaN               NaN
4     109307.0                0                   NaN               NaN
...        ...              ...                   ...               ...
5497  124815.0                0                   NaN               NaN
5498  124817.0                1                   NaN               NaN
5499  124818.0                1                   NaN               NaN
5500  124821.0                0                   NaN               NaN
5501  124822.0                0                   NaN              70.0

      fatty_liver  liver_fibrosis  liver_cirrhosis  liver_viral_hepatitis  \
0               0               0                0                      0
1               0               0                0                      0
2               0               0                0                      0
3               0               0                0                      0
4               0               0                0                      0
...           ...             ...              ...                    ...
5497            0               0                0                      0
5498            0               0                0                      0
5499            0               0                0                      0
5500            0               0                0                      0
5501            0               0                0                      0

      liver_autoimmune_hepatitis  other_liver_disease  ...  stroke  thyroid  \
0                              0                    0  ...       0        0
1                              0                    0  ...       0        0
2                              0                    0  ...       0        0
3                              0                    0  ...       0        0
4                              0                    0  ...       0        0
...                          ...                  ...  ...     ...      ...
5497                           0                    0  ...       0        0
5498                           0                    1  ...       0        0
5499                           0                    0  ...       0        0
5500                           0                    0  ...       0        0
5501                           0                    0  ...       0        0

      liver_disease  gallbladder_pr  Total_Cholesterol_mg_dL  \
0                 0               0                    195.0
1                 0               0                    105.0
2                 0               0                    172.0
3                 0               0                    214.0
4                 0               0                    161.0
...             ...             ...                      ...
5497              0               0                    203.0
5498              0               0                    200.0
5499              0               0                    234.0
5500              0               0                    155.0
5501              0               0                    171.0

      Frequency_of_Drinking  Drinks_per_Day  Work  Recreational  \
0                      10.0             1.0     0             1
1                       4.0             2.0     1             0
2                       4.0             6.0     0             0
3                       6.0             2.0     1             0
4                       9.0             1.0     0             0
...                     ...             ...   ...           ...
5497                    3.0             1.0     1             1
5498                    3.0             2.0     1             0
5499                    9.0             2.0     0             0
5500                    5.0             5.0     1             0
5501                    6.0             2.0     0             1

      100_Cigarettes
0                  0
1                  0
2                  0
3                  0
4                  1
...              ...
5497               1
5498               0
5499               0
5500               0
5501               0

[5502 rows x 27 columns]>

In [9]:
X = df.copy()
# X.drop('heart_attack_age', axis=1, inplace=True)
X.head()

,ever_overweight,blood_transfusion_yr,heart_attack_age,fatty_liver,liver_fibrosis,liver_cirrhosis,liver_viral_hepatitis,liver_autoimmune_hepatitis,other_liver_disease,relative_asthma,...,angina_pectoris,stroke,thyroid,liver_disease,gallbladder_pr,Frequency_of_Drinking,Drinks_per_Day,Work,Recreational,100_Cigarettes
0,1,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,10.0,1.0,0,1,0
1,1,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,4.0,2.0,1,0,0
2,0,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,4.0,6.0,0,0,0
3,0,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,6.0,2.0,1,0,0
4,0,NaN,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,9.0,1.0,0,0,1

In [10]:
# def replace_NaN(x):return x.fillna(1)
df.fillna(0, inplace=True)

In [11]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df['heart_attack_age']

# Separate the X variable, the features
X = df.drop('heart_attack_age', axis=1)

In [12]:
# Review the y variable Series
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: heart_attack_age, dtype: float64

In [13]:
# Review the x variable Series
X.head()

,ever_overweight,blood_transfusion_yr,fatty_liver,liver_fibrosis,liver_cirrhosis,liver_viral_hepatitis,liver_autoimmune_hepatitis,other_liver_disease,relative_asthma,relative_diabetes,...,angina_pectoris,stroke,thyroid,liver_disease,gallbladder_pr,Frequency_of_Drinking,Drinks_per_Day,Work,Recreational,100_Cigarettes
0,1,0.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,10.0,1.0,0,1,0
1,1,0.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,4.0,2.0,1,0,0
2,0,0.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,4.0,6.0,0,0,0
3,0,0.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,6.0,2.0,1,0,0
4,0,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,9.0,1.0,0,0,1

In [25]:
# Review the X variable DataFrame
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1e7)

In [26]:
# Check the balance of our target values
y.value_counts()

0.0     5303
55.0      11
60.0      10
80.0       9
47.0       8
59.0       8
40.0       8
52.0       7
54.0       6
49.0       6
50.0       6
61.0       6
56.0       6
58.0       6
42.0       5
45.0       5
53.0       5
33.0       4
51.0       4
16.0       4
72.0       4
37.0       4
65.0       4
48.0       4
62.0       4
35.0       4
67.0       3
68.0       3
26.0       3
70.0       3
63.0       3
64.0       3
44.0       3
43.0       3
46.0       2
41.0       2
69.0       2
73.0       2
36.0       2
75.0       2
57.0       2
74.0       2
77.0       1
38.0       1
71.0       1
34.0       1
30.0       1
79.0       1
32.0       1
21.0       1
39.0       1
29.0       1
19.0       1
Name: heart_attack_age, dtype: int64

In [27]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Assign a random_state of 1 to the function
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [28]:
# Display y train (counts)
y_train.value_counts()

0.0     3978
60.0       9
80.0       8
47.0       8
59.0       7
52.0       6
45.0       5
55.0       5
40.0       5
50.0       5
49.0       5
54.0       5
37.0       4
53.0       4
56.0       4
42.0       4
48.0       4
58.0       4
65.0       3
33.0       3
61.0       3
35.0       3
72.0       3
63.0       3
51.0       3
67.0       2
44.0       2
68.0       2
43.0       2
69.0       2
26.0       2
62.0       2
16.0       2
70.0       2
46.0       2
74.0       2
38.0       1
79.0       1
21.0       1
36.0       1
34.0       1
29.0       1
19.0       1
75.0       1
73.0       1
41.0       1
32.0       1
57.0       1
77.0       1
Name: heart_attack_age, dtype: int64

In [ ]:
# def replace_NaN(x):return x.fillna(1)

In [29]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model = LogisticRegression(random_state=1)

# Fit the model using training data
logistic_regression_model = logistic_regression_model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [30]:
# Make a prediction using the testing data
testing_prediction = logistic_regression_model.predict(X_test)

In [31]:
# Make a prediction using the testing data
testing_prediction = logistic_regression_model.predict(X_test)

In [32]:
# Print the balanced_accuracy score of the model
print(f"Training Data Score: {logistic_regression_model.score(X_train, y_train)}")
print(f"Testing Data Score: {logistic_regression_model.score(X_test, y_test)}")

Training Data Score: 0.9692195831313621
Testing Data Score: 0.9636627906976745

In [33]:
# Generate a confusion matrix for the model: 
from sklearn.metrics import confusion_matrix

In [34]:
# Print the classification report for the model
ros_testing_report = classification_report(y_test, testing_prediction)

print(ros_testing_report)

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99      1325
        16.0       0.00      0.00      0.00         2
        26.0       0.00      0.00      0.00         1
        30.0       0.00      0.00      0.00         1
        33.0       0.00      0.00      0.00         1
        35.0       0.00      0.00      0.00         1
        36.0       0.00      0.00      0.00         1
        39.0       0.00      0.00      0.00         1
        40.0       0.00      0.00      0.00         3
        41.0       0.00      0.00      0.00         1
        42.0       0.00      0.00      0.00         1
        43.0       0.00      0.00      0.00         1
        44.0       0.00      0.00      0.00         1
        45.0       0.00      0.00      0.00         0
        47.0       0.00      0.00      0.00         0
        49.0       0.00      0.00      0.00         1
        50.0       0.00      0.00      0.00         1
        51.0       0.00      0.00      0.00         1
        52.0       0.00      0.00      0.00         1
        53.0       0.00      0.00      0.00         1
        54.0       0.00      0.00      0.00         1
        55.0       0.00      0.00      0.00         6
        56.0       0.00      0.00      0.00         2
        57.0       0.00      0.00      0.00         1
        58.0       0.00      0.00      0.00         2
        59.0       0.00      0.00      0.00         1
        60.0       0.20      1.00      0.33         1
        61.0       1.00      0.33      0.50         3
        62.0       0.00      0.00      0.00         2
        63.0       0.00      0.00      0.00         0
        64.0       0.00      0.00      0.00         3
        65.0       0.00      0.00      0.00         1
        67.0       0.00      0.00      0.00         1
        68.0       0.00      0.00      0.00         1
        69.0       0.00      0.00      0.00         0
        70.0       0.00      0.00      0.00         1
        71.0       0.00      0.00      0.00         1
        72.0       0.00      0.00      0.00         1
        73.0       0.00      0.00      0.00         1
        75.0       0.00      0.00      0.00         1
        80.0       0.00      0.00      0.00         1

    accuracy                           0.96      1376
   macro avg       0.05      0.06      0.04      1376
weighted avg       0.94      0.96      0.95      1376

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))